language: java
sudo: false # faster builds
before_install:
- chmod +x mvnw
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: manimekalai8797-github
    token:
      secure: 88d571354e631041f3e2c1166f24cfd387ca71c6